<?php
// src/eveg/BiblioBundle/Controller/BaseBiblio/BaseBiblioRestController.php

namespace eveg\BiblioBundle\Controller\BaseBiblio;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use FOS\RestBundle\Controller\FOSRestController;
use JMS\Serializer\SerializationContext;
use FOS\RestBundle\Controller\Annotations\Get;

// routes are automaticly generated by FOSRestBundle using the name of a function
// ex : public function getTestAction will set up an 'api_get_test' route

class BaseBiblioRestController extends FOSRestController
{
	/**
	 * GET Route annotation.
	 * @Get("/biblio")
	 */
	public function getBaseBiblioAction(Request $request)
	{

		// Get host name
		//$hostName = $request->getHost();

		// New view
		$view = $this->view();
		$view->setSerializationContext(SerializationContext::create());

		// Grabbing SyntaxonCore repository
		$em         = $this->getDoctrine()->getManager();
		$biblioRepo = $em->getRepository('evegBiblioBundle:BaseBiblio');

		// Find syntaxon
		$references = $biblioRepo->findAll();


		// Return
		$view->setData($references);
		return $view;

	}
}