<?php

namespace eveg\BiblioBundle\Entity;

/**
 * BaseBiblioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseBiblioRepository extends \Doctrine\ORM\EntityRepository
{
}
