<?php

namespace eveg\BiblioBundle\Entity;

/**
 * BiblioFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiblioFileRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLastFiles($limit)
	{
		$qb = $this->createQueryBuilder('b');

		$qb->select('b')
		   ->orderBy('b.updatedAt', 'DESC')
		   ->setMaxResults($limit);

		return $qb->getQuery()->getResult();
	}

	public function getNbFiles()
	{
		$qb = $this->createQueryBuilder('b');

		$qb->select('COUNT(b)');

		return $qb->getQuery()->getSingleScalarResult();
	}
}
