services:
    user_repartition.merge:
        class:             eveg\UserRepartitionBundle\Utils\mergeUserRepartitions
        arguments:         ['@score_repository', '@user_repartition_repository']

    user_repartition.conflicts:
        class:             eveg\UserRepartitionBundle\Utils\conflictsHelpers
        arguments:         ['@score_repository', '@user_repartition_repository', '@user_repartition.merge', '@doctrine.orm.default_entity_manager']

    user_repartition.tables_helper:
        class:             eveg\UserRepartitionBundle\Utils\tablesHelpers

    user_repartition.twig.extension:
        class:             eveg\UserRepartitionBundle\Twig\userRepartitionExtension
        arguments:         ['@user_repartition.conflicts', '@user_repartition.tables_helper']
        tags:
            - { name: twig.extension }

    user_repartition.form.type.add_repartition:
        class:              eveg\UserRepartitionBundle\Form\Type\RepartitionType
        arguments:          ['@user_repartition.tables_helper']
        tags:
            - {name: form.type }

    ############
    # Repository
    ############
    user_repartition_repository:
        class:              Doctrine\ORM\EntityRepository
        factory:           ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - eveg\UserRepartitionBundle\Entity\Repartition