services:
    user_repartition.merge:
        class:             eveg\UserRepartitionBundle\Utils\mergeUserRepartitions
        arguments:         ['@score_repository', '@user_repartition_repository']

    user_repartition.conflicts:
        class:             eveg\UserRepartitionBundle\Utils\conflictsHelpers
        arguments:         ['@score_repository', '@user_repartition_repository', '@user_repartition.merge', '@doctrine.orm.default_entity_manager']

    ############
    # Repository
    ############
    user_repartition_repository:
        class:              Doctrine\ORM\EntityRepository
        factory:           ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - eveg\UserRepartitionBundle\Entity\Repartition