# routes prefix: /admin/repartition

eveg_user_repartition_list_enabled_and_active:
    path: /list
    defaults: { _controller: evegUserRepartitionBundle:Admin:ListEnabledAndActive }

eveg_user_repartition_list_disabled_or_unactive:
    path: /list/disabled-or-unactive
    defaults: { _controller: evegUserRepartitionBundle:Admin:ListDisabledOrUnactive }

eveg_user_repartition_admin_conflicts:
    path: /conflicts
    defaults: { _controller: evegUserRepartitionBundle:Admin:conflictsIndex }

eveg_user_repartition_admin_unresolved:
    path: /unresolved
    defaults: { _controller: evegUserRepartitionBundle:Admin:unresolvedRepartitions }

eveg_repartition_validate_data:
    path: /{id}/validate
    defaults: { _controller: evegUserRepartitionBundle:Admin:validateRepartition }

eveg_repartition_unvalidate_data:
    path: /{id}/unvalidate
    defaults: { _controller: evegUserRepartitionBundle:Admin:unvalidateRepartition }

eveg_repartition_enable_data:
    path: /{id}/enable
    defaults: { _controller: evegUserRepartitionBundle:Admin:enableRepartition }

eveg_repartition_disable_data:
    path: /{id}/disable
    defaults: { _controller: evegUserRepartitionBundle:Admin:disableRepartition }