<?php

namespace eveg\PagesBundle\Entity;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTitleSlugFr($slug)
	{
		$qb = $this->createQueryBuilder('p');

		// specify the fields to fetch (unselected fields will have a null value)
		$qb->select('p')
		   ->where('p.titleSlugFr = :slug')
		   ->andWhere('p.published = :true')
		   ->setParameter('slug', $slug)
		   ->setParameter('true', true)
		;

		return $qb->getQuery()->getSingleResult();
	}

	public function findForMenu()
	{
		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
		   ->where('p.published = :true')
		   ->setParameter('true', true)
		;

		return $qb->getQuery()->getResult();
	}

}
