<?php

namespace eveg\PagesBundle\Entity;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTitleSlugFr($slug)
	{
		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
		   ->where('p.titleSlugFr = :slug')
		   ->andWhere('p.published = :true')
		   ->setParameter('slug', $slug)
		   ->setParameter('true', true)
		;

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findByTitleSlugEn($slug)
	{
		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
		   ->where('p.titleSlugEn = :slug')
		   ->andWhere('p.published = :true')
		   ->setParameter('slug', $slug)
		   ->setParameter('true', true)
		;

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findForMenu()
	{
		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
		   ->where('p.published = :true')
		   ->setParameter('true', true)
		   ->orderBy('p.listOrder', 'ASC')
		;

		return $qb->getQuery()->getResult();
	}

	public function findAll()
	{
		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
		   ->orderBy('p.listOrder', 'ASC')
		;

		return $qb->getQuery()->getResult();
	}

	public function findBySection($section)
	{
		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
		   ->where('p.section = :section')
		   ->andWhere('p.published = :true')
		   ->setParameter('section', $section)
		   ->setParameter('true', true)
		   ->orderBy('p.listOrder', 'ASC')
		;

		return $qb->getQuery()->getResult();
	}

}
