<?php

namespace eveg\PagesBundle\Entity;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByTitleSlugFr($slug)
	{
		$qb = $this->createQueryBuilder('s');

		$qb->select('s')
		   ->where('s.titleSlugFr = :slug')
		   ->andWhere('s.active = :true')
		   ->setParameter('slug', $slug)
		   ->setParameter('true', true)
		;

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findByTitleSlugEn($slug)
	{
		$qb = $this->createQueryBuilder('s');

		$qb->select('s')
		   ->where('s.titleSlugEn = :slug')
		   ->andWhere('p.active = :true')
		   ->setParameter('slug', $slug)
		   ->setParameter('true', true)
		;

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findForMenu()
	{
		$qb = $this->createQueryBuilder('s');

		$qb->select('s')
		   ->where('s.active = :true')
		   ->setParameter('true', true)
		   ->orderBy('s.listOrder', 'ASC')
		;

		return $qb->getQuery()->getResult();
	}

	public function findAll()
	{
		$qb = $this->createQueryBuilder('s');

		$qb->select('s')
		   ->orderBy('s.listOrder', 'ASC')
		;

		return $qb->getQuery()->getResult();
	}
}
