<?php
// src/eveg/PsiBundle/Controller/PsiRestController.php

namespace eveg\PsiBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Controller\Annotations\Get;
//use JMS\Serializer\SerializationContext;

// routes are automaticly generated by FOSRestBundle using the name of a function
// ex : public function getTestAction will set up an 'api_get_test' route

class PsiRestController extends FOSRestController
{
	/**
	 * GET Route annotation.
	 * @Get("/node/")
	 */
	public function getNodeAction()
	{
		// New view
		$view = $this->view();
		//$view->setSerializationContext(SerializationContext::create()->setGroups(array('API')));

		// Grabbing SyntaxonCore repository
		$em = $this->getDoctrine()->getManager();
		$scRepo = $em->getRepository('evegPsiBundle:Pattern');

		// Find syntaxon
		$patterns = $scRepo->findAll();

		// Check if unique result
		//...

		// Return
		$view->setData($patterns);
		return $view;

	}
}