#src/eveg/AppBundle/Resources/config/routing/routing_rest.yml

rest_syntaxon_tree: 
    type: rest
    resource:     "evegAppBundle:SyntaxonTreeRest"
    name_prefix: api_

rest_syntaxon_tb: 
    type: rest
    resource:     "evegAppBundle:SyntaxonTbRest"
    name_prefix: api_