# src/eveg/AppBundle/Resources/config/routing_admin.yml

# Admin routes
eveg_admin_dashboard:
    path: /
    defaults: { _controller: evegAppBundle:Admin:dashboard }

eveg_admin_test:
    path: /test
    defaults: { _controller: evegAppBundle:Admin:test }

eveg_admin_documents:
    path: /documents
    defaults: { _controller: evegAppBundle:Admin:listDocuments }

eveg_admin_users:
    path: /users
    defaults: { _controller: evegAppBundle:Admin:users }

eveg_admin_edit_user:
    path: /user/{id}
    defaults: { _controller: evegUserBundle:Profile:editAdmin }

eveg_admin_delete_user:
    path: /user/{id}/delete
    defaults: { _controller: evegAppBundle:Admin:deleteUser }

eveg_admin_import_baseveg_repartitionDepFr:
    path: /import/dep_fr
    defaults: { _controller: evegAppBundle:Import:importRepartitionDepFr }

eveg_admin_import_baseveg_repartitionEurope:
    path: /import/europe
    defaults: { _controller: evegAppBundle:Import:importRepartitionEurope }

eveg_admin_import_baseveg_core:
    path: /import/core
    defaults: { _controller: evegAppBundle:Import:importCore }

eveg_admin_import_baseveg_biblio:
    path: /import/biblio
    defaults: { _controller: evegAppBundle:Import:importBiblio }

eveg_admin_import_baseveg_ecology:
    path: /import/ecologie
    defaults: { _controller: evegAppBundle:Import:importEcology }

eveg_admin_import_baseflor:
    path: /import/baseflor
    defaults: { _controller: evegAppBundle:Import:importBaseflor }

eveg_admin_import_logs:
    path: /import/logs
    defaults: { _controller: evegAppBundle:Import:logs }

eveg_admin_versioning:
    path: /baseveg/versioning/list
    defaults: { _controller: evegAppBundle:Versioning:list }

eveg_admin_versioning_id:
    path: /baseveg/versioning/syntaxon/{id}
    defaults: { _controller: evegAppBundle:Versioning:showOne }

eveg_admin_infos:
    path: /infos
    defaults: { _controller: evegAppBundle:Admin:infos }

#eveg_slug_regenerator:
#    path: /regenerate-slugs
#    defaults: { _controller: evegAppBundle:Admin:generateAllSlugs }

# Dev routes
eveg_admin_catCode:
    path: /catcode_test
    defaults: { _controller: evegAppBundle:Admin:devCatCode }

eveg_app_admin_syntaxon:
    resource: "@evegAppBundle/Resources/config/routing/syntaxoncore.yml"
    prefix:   /syntaxon