<?php
// src/eveg/AppBundle/Controller/SyntaxonSearchRestController.php

namespace eveg\AppBundle\Controller;

use FOS\RestBundle\Controller\Annotations\View;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use FOS\RestBundle\Controller\FOSRestController;
use JMS\Serializer\SerializationContext;
use FOS\RestBundle\Controller\Annotations\Get;


// routes are automaticly generated by FOSRestBundle using the name of a function
// ex : public function getTestAction will set up an 'api_get_test' route

// How to use Groups (JMSSerializer) with FosRestBundle : http://stackoverflow.com/questions/21413143/how-to-get-groups-working-for-jmsserializerbundle-and-fosrestbundle


// TO BE DELETED !!!!!!!!!!
class SyntaxonSearchRestController extends FOSRestController
{
	public function getSyntaxonSearchDeleteAction($searchedTerm, $useSynonyms = true)
	{

		$view = $this->view();
	    $view->setSerializationContext(SerializationContext::create()->setGroups(array('searchEngine')));

	    $searchedTerm = $searchedTerm . ' ';
	    $searchedTerm = str_replace(' ', '%', $searchedTerm);

	    $result = $this->getDoctrine()
	    			   ->getManager()
	    			   ->getRepository('evegAppBundle:SyntaxonCore')
	    			   ->findForSearchEngine($searchedTerm, $useSynonyms);

	    if(empty($result)){
	    	//$result = null;
	    }

	$view->setData($result);
    return $view;

	}
}