<?php
// src/eveg/AppBundle/Controller/SyntaxonRestController.php

namespace eveg\AppBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use FOS\RestBundle\Controller\FOSRestController;
use JMS\Serializer\SerializationContext;
use FOS\RestBundle\Controller\Annotations\Get;

// routes are automaticly generated by FOSRestBundle using the name of a function
// ex : public function getTestAction will set up an 'api_get_test' route

class SyntaxonTbRestController extends FOSRestController
{
	/**
	 * GET Route annotation.
	 * @Get("/tb/syntaxon/{id}")
	 */
	public function getSyntaxonAction($id, Request $request)
	{

		// Get host name
		$hostName = $request->getHost();
		// Check if host is TB or if you're logged in as super-admin
		if(($hostName !== $this->container->getParameter('eveg')['tb_host']) and (!$this->get('security.authorization_checker')->isGranted('ROLE_SUPER_ADMIN'))) Throw new AccessDeniedHttpException();

		// New view
		$view = $this->view();
		$view->setSerializationContext(SerializationContext::create()->setGroups(array('API')));

		// Grabbing SyntaxonCore repository
		$em = $this->getDoctrine()->getManager();
		$scRepo = $em->getRepository('evegAppBundle:SyntaxonCore');

		// Find syntaxon
		$syntaxon = $scRepo->findById($id);

		// Check if unique result
		//...

		// Return
		$view->setData($syntaxon);
		return $view;

	}
}