<?php
// src/eveg/AppBundle/Controller/SyntaxonRestController.php

namespace eveg\AppBundle\Controller;

use FOS\RestBundle\Controller\FOSRestController;
use JMS\Serializer\SerializationContext;

// routes are automaticly generated by FOSRestBundle using the name of a function
// ex : public function getTestAction will set up an 'api_get_test' route

class SyntaxonRestController extends FOSRestController
{
	public function getSyntaxonAction($id)
	{

		// New view
		$view = $this->view();
		$view->setSerializationContext(SerializationContext::create()->setGroups(array('API')));

		// Grabbing SyntaxonCore repository
		$em = $this->getDoctrine()->getManager();
		$scRepo = $em->getRepository('evegAppBundle:SyntaxonCore');

		// Find syntaxon
		$syntaxon = $scRepo->findById($id);

		// Check if unique result
		//...

		// Return
		$view->setData($syntaxon);
		return $view;

	}
}