<?php

namespace eveg\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByIdWithDocs($id)
	{
		$qb = $this->createQueryBuilder('u');

		$qb->where('u.id = :id')
		   ->leftJoin('u.syntaxonFiles', 'sFiles')
		   ->leftJoin('u.syntaxonHttpLinks', 'sHttpLinks')
		   ->leftJoin('u.syntaxonPhotos', 'sPhotos')
		   ->setParameter('id', $id)
		   ->addSelect('sFiles')
		   ->addSelect('sHttpLinks')
		   ->addSelect('sPhotos');

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findAllUsersWithTotalScore($limitResults = null)
	{
		$qb = $this->createQueryBuilder('u');

		$qb->select('u');
		$qb->addSelect('SUM(u.nbSyntaxonFiles) + SUM(u.nbSyntaxonHttpLinks) + SUM(u.nbSyntaxonPhotos) + SUM(u.nbFeedbacks) As TotalScore')
		   ->orderBy('TotalScore', 'DESC')
		   ->groupBy('u');

		if($limitResults) {
			$qb->setMaxResults($limitResults);
		}

		return $qb->getQuery()->getResult();
	}

	public function findUsersEmailsForNewsletter()
	{
		$qb = $this->createQueryBuilder('u');

		$qb->select('u.email');

		return $qb->getQuery()->getResult();
	}
}
