<?php

namespace eveg\UserRepartitionBundle\Entity;

/**
 * RepartitionConflictItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepartitionConflictItemRepository extends \Doctrine\ORM\EntityRepository
{
}
