<?php

namespace eveg\UserRepartitionBundle\Entity;

/**
 * RepartitionConflictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepartitionConflictRepository extends \Doctrine\ORM\EntityRepository
{
}
