<?php

namespace eveg\UserRepartitionBundle\Entity;

/**
 * RepartitionConflictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepartitionConflictRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOpenedConflicts()
	{
		$qb = $this->createQueryBuilder('c');

		$qb->select('c')
		   ->where('c.resolved = :false')
		   ->setParameter('false', false)
		   ->leftJoin('c.beetweenRepartition', 'beetweenRepartition')
		   ->leftJoin('c.andRepartition', 'andRepartition')
		   ->addSelect('beetweenRepartition')
		   ->addSelect('andRepartition')
		;

		return $qb->getQuery()->getResult();
	}
}
