<?php

namespace eveg\UserRepartitionBundle\Entity;

/**
 * RepartitionBundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepartitionRepository extends \Doctrine\ORM\EntityRepository
{
}
