<?php

namespace eveg\AppBundle\Entity;

/**
 * BaseflorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseflorRepository extends \Doctrine\ORM\EntityRepository
{
}
