<?php

namespace eveg\AppBundle\Entity;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLastFeedbacks($limitResults = 10)
	{
		$qb = $this->createQueryBuilder('f');

		$qb->orderBy('f.date', 'DESC');

		if($limitResults) {
			$qb->setMaxResults($limitResults);
		}

		return $qb->getQuery()->getResult();
	}
}
