<?php

namespace eveg\AppBundle\Entity;

/**
 * ImportLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportLogRepository extends \Doctrine\ORM\EntityRepository
{
}
