<?php

namespace eveg\AppBundle\Entity;

/**
 * ImportLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportLogRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll($limitItems = null)
	{
		$qb = $this->createQueryBuilder('l');

		$qb->select('l')
		   ->orderBy('l.date', 'DESC');

		if($limitItems != null) {
			$qb->setMaxResults($limitItems);
		}

		return $qb->getQuery()->getResult();
	}

	public function findGroupedByDate($limitItems = null)
	{
		$qb = $this->createQueryBuilder('l');

		$qb->select('l')
		   ->groupBy('l.date')
		   ->orderBy('l.date', 'DESC');

		if($limitItems != null) {
			$qb->setMaxResults($limitItems);
		}

		return $qb->getQuery()->getResult();
	}
}
