<?php

namespace eveg\AppBundle\Entity;

/**
 * syntaxonRepartitionDepFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class syntaxonRepartitionDepFrRepository extends \Doctrine\ORM\EntityRepository
{
}
