<?php

namespace eveg\AppBundle\Entity;

/**
 * SyntaxonHttpLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyntaxonHttpLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
