<?php

namespace eveg\AppBundle\Entity;

/**
 * SyntaxonRepartitionEuropeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyntaxonRepartitionEuropeRepository extends \Doctrine\ORM\EntityRepository
{
}
