<?php

namespace eveg\AppBundle\Entity;

/**
 * SyntaxonEcologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyntaxonEcologyRepository extends \Doctrine\ORM\EntityRepository
{
}
