<?php

namespace eveg\AppBundle\Entity;

/**
 * SyntaxonPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyntaxonPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
