<?php

namespace eveg\AppBundle\Entity;

/**
 * SyntaxonFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyntaxonFileRepository extends \Doctrine\ORM\EntityRepository
{
}
