<?php

namespace eveg\AppBundle\Entity;

/**
 * SyntaxonNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyntaxonNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
